export const profileData = {
  name: "Putra Prassiesa Abimanyu",
  jobTitle: "Fullstack Developer",
  tagline: "Building digital gardens",
  bio: "Fullstack developer focused on resilient backends, thoughtful interfaces, and quietly fast experiences for the web.",
  tackStack: [
    "Golang",
    "Node.JS",
    "Javascript",
    "Typescript",
    "React",
    "Next.JS",
    "Nest.JS",
    "PortgreSQL",
    "MySQL",
    "SQLServer",
    "MonggoDB",
    "Redis",
    "Kafka",
    "Docker",
    "Kubernetes",
    "React Native",
  ],
  profileUrl: "https://avatars.githubusercontent.com/u/71804682?v=4",
  linkedIn: "https://www.linkedin.com/in/ppabimanyu/",
  github: "https://github.com/ppabimanyu",
  email: "ppabimanyu@gmail.com",
  location: "Jember, East Java, Indonesia",
};
